# Generated by Django 5.1.5 on 2025-02-04 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_serviceprovider_delete_assistancerequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceprovider',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='serviceprovider',
            name='longitude',
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='mobile_number',
            field=models.CharField(default=9087643567, max_length=15),
            preserve_default=False,
        ),
    ]
