# Generated by Django 5.1.5 on 2025-02-04 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_location_alter_serviceprovider_location_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceprovider',
            name='location_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
